name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" 

jobs:
  auto_commit:
    name: "Auto push commits to my repo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout repository

      - name: Set up Git user
        run: |
          git config --global user.name "nphng15"
          git config --global user.email "23521172@gm.uit.edu.vn"

      - name: Decide whether to commit today
        id: skip_commit
        run: |
          SKIP_PROB=$(python3 -c "import random; print(random.choices([0, 1], weights=[70, 30])[0])")
          echo "Skip commit today? $SKIP_PROB"
          echo "SKIP=$SKIP_PROB" >> $GITHUB_ENV

      - name: Exit if skipping commit
        if: env.SKIP == '1'
        run: echo "Skipping commit for today" && exit 0

      - name: Generate random number of commits (1-30, 5% chance for 20-30 commits, 20% chance for 10-20 commits)
        id: random_commit_count
        run: |
          RANDOM_NUM=$(python3 -c "import random; print(random.choices(list(range(1, 31)), weights=[75]*10 + [20]*10 + [5]*10)[0])")
          echo "Total commits today: $RANDOM_NUM"
          echo "COMMITS=$RANDOM_NUM" >> $GITHUB_ENV

      - name: Generate and push commits
        run: |
          for i in $(seq 1 $COMMITS)
          do
            # Tạo chuỗi ngẫu nhiên (16 ký tự chữ và số)
            RANDOM_STRING=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
            echo "$RANDOM_STRING" >> report.txt

            git add report.txt
            git commit -m "$RANDOM_STRING"
            git push 

            SLEEP_TIME=$((RANDOM % 600 + 300))  # Ngủ từ 5 đến 10 phút
            echo "Sleeping for $SLEEP_TIME seconds before the next commit..."
            sleep $SLEEP_TIME
          done
