name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" 

jobs:
  auto_commit:
    name: "Auto push commits to my repo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout repository

      - name: Set up Git user
        run: |
          git config --global user.name "nphng15"
          git config --global user.email "23521172@gm.uit.edu.vn"

      - name: Decide whether to commit today
        id: skip_commit
        run: |
          SKIP_PROB=$(python3 -c "import random; print(random.choices([0, 1], weights=[70, 30])[0])")
          echo "Skip commit today? $SKIP_PROB"
          echo "SKIP=$SKIP_PROB" >> $GITHUB_ENV

      - name: Exit if skipping commit
        if: env.SKIP == '1'
        run: echo "Skipping commit for today" && exit 0

      - name: Generate random number of commits (1-20, 10% chance for 10-20 commits)
        id: random_commit_count
        run: |
          RANDOM_NUM=$(python3 -c "import random; print(random.choices(list(range(1, 21)), weights=[9]*9 + [1]*11)[0])")
          echo "Total commits today: $RANDOM_NUM"
          echo "COMMITS=$RANDOM_NUM" >> $GITHUB_ENV

      - name: Generate and push commits
        run: |
          for i in $(seq 1 $COMMITS)
          do

            COMMIT_TIME=$(TZ="Asia/Bangkok" date +"%Y-%m-%d %H:%M:%S GMT+7")
            echo "Commit #$i at $COMMIT_TIME" >> report.txt

            git add report.txt
            git commit -m "#$i at $COMMIT_TIME"
            git push 

            SLEEP_TIME=$((RANDOM % 600 + 300))  # 300 seconds = 5 minutes, 600 seconds = 10 minutes
            echo "Sleeping for $SLEEP_TIME seconds before the next commit..."
            sleep $SLEEP_TIME
          done
